### ISSUE TITLE
OperationOutcome?

### ISSUE THREAD

**Issue by brpr** [smart-on-fhir/fhir-parser#12]
Hello, I’m using the following Construction 

v = ValueSet.read(some_id, fhirserver)

In case then all go right and Resource from  some_id was founded,  then v - object ValueSet.

But in case then request_json() return from server  json with resourceType = OperationOutcome -  v keep the same object ValueSet.

May be I misuse this function in some way ?

**Comment by p2** [comment]
This issue does not concern the parser, this should be in [client-py](https://github.com/smart-on-fhir/client-py).

In any case: when you're getting a 200 with a *different* resource type, then there will probably be many errors because the model doesn't match. If you're getting an error (400+) and an `OperationOutcome`, then an exception will be thrown. This is not yet nicely handled and should be improved.

**Comment by brpr** [comment]
It’s Construction at FHIRAbstractResource.read_from()

ret = server.request_json(path)
instance = cls(jsondict=ret)
instance._server = server
return instance

But **ret** can include icon of Recourse witch differ from cls (ValueSet etc.),
and in the code above namely ValueSet ultimately created, if ValueSet.read() was called.

FHIRAbstractResource include method _with_json_dict(), can this method been used for creating new item ? (now it isn’n)

instance = cls._with_json_dict(jsondict=ret)

Can’t make sense from it, can it be a mistake ?

**Comment by p2** [comment]
Four things:

- `server.request_json()` will throw an exception on `>= 400`
- `cls(jsondict={})` is the way to instantiate a resource from JSON directly
- `cls.read_from(path)` is the way to instantiate a resource remotely; *you* are responsible to use the correct type
- To be sure you automacitally get the correct type, use `FHIRElementFactory.instantiate(resourceType, jsondict)`

Does this answer your question?

**Comment by brpr** [comment]
Ok. Thank you
